#!/usr/bin/env python3
"""render-readme-packages.py — render the README package map from skills/packages.json.

The map cannot drift from the manifest: package membership, blurbs, budgets and
requires come from the manifest; per-skill text comes from each member's SKILL.md
frontmatter `description` (parsed with lint/lib/frontmatter.py, the one parser —
never a second copy). Run from the repo root; rewrites README.md in place between
the PACKAGES markers. Fails loud (non-zero + named reason) when the manifest is
missing/unreadable, a member names a dir without SKILL.md, or the markers are
absent — a map that rendered nothing is never written.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "skills", "packages.json")
README = os.path.join(ROOT, "README.md")
BEGIN = "<!-- PACKAGES:BEGIN -->"
END = "<!-- PACKAGES:END -->"

sys.path.insert(0, os.path.join(ROOT, "lint", "lib"))
import frontmatter  # noqa: E402  (the one frontmatter parser; see module docstring)


def fail(msg):
    print(f"render-readme-packages: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def cell(text):
    return re.sub(r"\s+", " ", text).replace("|", "\\|").strip()


def main():
    try:
        with open(MANIFEST, encoding="utf-8") as fh:
            manifest = json.load(fh)
    except FileNotFoundError:
        fail(f"manifest missing: {MANIFEST}")
    except json.JSONDecodeError as e:
        fail(f"manifest unreadable (malformed JSON): {MANIFEST}: {e}")
    if not isinstance(manifest, dict):
        fail(f"manifest not an object: {MANIFEST}")

    packages = [(k, v) for k, v in manifest.items() if not k.startswith("_")]
    if len(packages) != 7:
        fail(f"manifest declares {len(packages)} packages, expected 7")

    out = [BEGIN,
           "<!-- generated by scripts/render-readme-packages.py from skills/packages.json; do not hand-edit — edit the manifest, then re-run -->",
           ""]
    for name, pkg in packages:
        for field in ("blurb", "skills", "budget"):
            if field not in pkg:
                fail(f"package '{name}' lacks '{field}'")
        members = pkg["skills"]
        if not members:
            fail(f"package '{name}' names zero skills; the map would claim an empty package")
        out.append(f"**{name}** — {pkg['blurb']}.")
        out.append("| Skill | What it does |")
        out.append("|-------|-------------|")
        for skill in members:
            skill_md = os.path.join(ROOT, "skills", skill, "SKILL.md")
            if not os.path.isfile(skill_md):
                fail(f"package '{name}' names '{skill}' with no skills/{skill}/SKILL.md — the map never names a dead skill")
            with open(skill_md, encoding="utf-8") as fh:
                desc = frontmatter.parse(fh.read()).get("description", "")
            if not desc:
                fail(f"skills/{skill}/SKILL.md carries no frontmatter description; the map has no text to render")
            out.append(f"| **[{skill}](./skills/{skill}/)** | {cell(desc)} |")
        budget = pkg["budget"]
        footer = f"*budget: spine ≤{budget['spine']}, loaded ≤{budget['loaded']}*"
        if pkg.get("requires"):
            footer += f" · *requires: {', '.join(pkg['requires'])}*"
        out.append("")
        out.append(footer)
        out.append("")
    out.append(END)

    try:
        with open(README, encoding="utf-8") as fh:
            readme = fh.read()
    except FileNotFoundError:
        fail(f"README missing: {README}")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(readme):
        fail(f"README carries no {BEGIN} … {END} block; refusing to guess where the map goes")
    readme = pattern.sub("\n".join(out), readme)
    with open(README, "w", encoding="utf-8") as fh:
        fh.write(readme)
    print(f"render-readme-packages: rendered {len(packages)} packages into README.md")


if __name__ == "__main__":
    main()
